# Generated by Django 2.1.7 on 2019-07-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190715_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='author_name',
        ),
    ]
