# Generated by Django 2.1.7 on 2019-07-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190715_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='head0',
            new_name='headline',
        ),
    ]
