# Generated by Django 2.1.7 on 2019-07-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190715_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='head1',
            new_name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead0',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
    ]
