# Generated by Django 2.1.7 on 2019-07-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_blogpost_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
    ]
